# Travic-CI-Config file for Manero
#
sudo: false
language: php

php:
 - 7.2
 - 7.3
 - nightly

env:
 - DEPS=latest

matrix:
  fast_finish : true
  allow_failures:
      - php: nightly
  include:
    - php: 7.3
      env:
        - TEST_COVERAGE=true
        - CHECK_CS=false

stages:
  - check
  - test
  - coverage

jobs:
  include:
    - stage: check
      php: 7.3
      script:
        - composer cs-check
    - stage: test
    - stage: coverage
      if: branch = master AND type = push
      php: 7.3
      env: TEST_COVERAGE=true
      script: skip
      after_script:
       - travis_retry composer require $COMPOSER_ARGS --dev satooshi/php-coveralls ;
       - composer test-coverage
       - travis_retry composer upload-coverage

before_install:
  # Manually compile the libsodium library
  - git clone -b stable https://github.com/jedisct1/libsodium.git
  - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
  - travis_retry composer self-update
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - pecl install libsodium
  - echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

script:
  - composer test
