name: Password-Workflow
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest # ${{ matrix.operating-system }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        # operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['7.2', '7.3', '7.4', '8.0']
        experimental: [false]
        include:
          - php-versions: '8.1'
            experimental: true
    name: PHP ${{ matrix.php-versions }} # Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: sodium
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
      - name: prepare
        run: composer update

      - name: test
        run: ./vendor/bin/phpunit

      - name: check
        run: ./vendor/bin/phpcs

